// Maps English national-team names (as returned by football-data.org) to Persian.
// Falls back to the original name if not found.
const TEAMS_FA: Record<string, string> = {
  Argentina: "آرژانتین",
  Australia: "استرالیا",
  Austria: "اتریش",
  Belgium: "بلژیک",
  Brazil: "برزیل",
  Cameroon: "کامرون",
  Canada: "کانادا",
  Colombia: "کلمبیا",
  "Costa Rica": "کاستاریکا",
  Croatia: "کرواسی",
  Denmark: "دانمارک",
  Ecuador: "اکوادور",
  Egypt: "مصر",
  England: "انگلیس",
  France: "فرانسه",
  Germany: "آلمان",
  Ghana: "غنا",
  Iran: "ایران",
  "IR Iran": "ایران",
  Italy: "ایتالیا",
  "Ivory Coast": "ساحل عاج",
  "Côte d'Ivoire": "ساحل عاج",
  "Cote d'Ivoire": "ساحل عاج",
  Japan: "ژاپن",
  "South Korea": "کره جنوبی",
  "Korea Republic": "کره جنوبی",
  Korea: "کره جنوبی",
  Mexico: "مکزیک",
  Morocco: "مراکش",
  Netherlands: "هلند",
  "New Zealand": "نیوزیلند",
  Nigeria: "نیجریه",
  Norway: "نروژ",
  Paraguay: "پاراگوئه",
  Peru: "پرو",
  Poland: "لهستان",
  Portugal: "پرتغال",
  Qatar: "قطر",
  "Saudi Arabia": "عربستان",
  Senegal: "سنگال",
  Serbia: "صربستان",
  Spain: "اسپانیا",
  "South Africa": "آفریقای جنوبی",
  Sweden: "سوئد",
  Switzerland: "سوئیس",
  Tunisia: "تونس",
  Turkey: "ترکیه",
  Türkiye: "ترکیه",
  Ukraine: "اوکراین",
  Uruguay: "اروگوئه",
  USA: "آمریکا",
  "United States": "آمریکا",
  Wales: "ولز",
  Algeria: "الجزایر",
  Chile: "شیلی",
  "Czech Republic": "جمهوری چک",
  Czechia: "جمهوری چک",
  Greece: "یونان",
  Hungary: "مجارستان",
  Romania: "رومانی",
  Scotland: "اسکاتلند",
  Panama: "پاناما",
  Jamaica: "جامائیکا",
  Honduras: "هندوراس",
  "DR Congo": "کنگو دموکراتیک",
  "Congo DR": "کنگو دموکراتیک",
  "Democratic Republic of the Congo": "کنگو دموکراتیک",
  Congo: "کنگو",
  "Cape Verde": "کیپ‌ورد",
  "Cape Verde Islands": "کیپ‌ورد",
  Jordan: "اردن",
  Uzbekistan: "ازبکستان",
  "United Arab Emirates": "امارات",
  UAE: "امارات",
  Iraq: "عراق",
  Bolivia: "بولیوی",
  Venezuela: "ونزوئلا",
  "Bosnia-Herzegovina": "بوسنی و هرزگوین",
  "Bosnia and Herzegovina": "بوسنی و هرزگوین",
  "Curaçao": "کوراسائو",
  Haiti: "هائیتی",
  Angola: "آنگولا",
  "Burkina Faso": "بورکینافاسو",
  Mali: "مالی",
  Guinea: "گینه",
  Zambia: "زامبیا",
  Gabon: "گابن",
  Georgia: "گرجستان",
  Slovakia: "اسلوواکی",
  Slovenia: "اسلوونی",
  Albania: "آلبانی",
  "North Macedonia": "مقدونیه شمالی",
  Finland: "فنلاند",
  "El Salvador": "السالوادور",
  Guatemala: "گواتمالا",
  "Trinidad and Tobago": "ترینیداد و توباگو",
  "Trinidad & Tobago": "ترینیداد و توباگو",
  Iceland: "ایسلند",
  "Republic of Ireland": "ایرلند",
  Ireland: "ایرلند",
  "Northern Ireland": "ایرلند شمالی",
  China: "چین",
  "China PR": "چین",
  Oman: "عمان",
  Syria: "سوریه",
  Palestine: "فلسطین",
  Lebanon: "لبنان",
  Bahrain: "بحرین",
  Kuwait: "کویت",
  Yemen: "یمن",
  "North Korea": "کره شمالی",
  "Korea DPR": "کره شمالی",
  "DPR Korea": "کره شمالی",
  Vietnam: "ویتنام",
  Thailand: "تایلند",
  Indonesia: "اندونزی",
  Kyrgyzstan: "قرقیزستان",
  "Kyrgyz Republic": "قرقیزستان",
  Tajikistan: "تاجیکستان",
  India: "هند",
};

const TEAMS_FLAG: Record<string, string> = {
  Argentina: "🇦🇷",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  Brazil: "🇧🇷",
  Cameroon: "🇨🇲",
  Canada: "🇨🇦",
  Colombia: "🇨🇴",
  "Costa Rica": "🇨🇷",
  Croatia: "🇭🇷",
  Denmark: "🇩🇰",
  Ecuador: "🇪🇨",
  Egypt: "🇪🇬",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Ghana: "🇬🇭",
  Iran: "🇮🇷",
  "IR Iran": "🇮🇷",
  Italy: "🇮🇹",
  "Ivory Coast": "🇨🇮",
  "Côte d'Ivoire": "🇨🇮",
  "Cote d'Ivoire": "🇨🇮",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  "Korea Republic": "🇰🇷",
  Korea: "🇰🇷",
  Mexico: "🇲🇽",
  Morocco: "🇲🇦",
  Netherlands: "🇳🇱",
  "New Zealand": "🇳🇿",
  Nigeria: "🇳🇬",
  Norway: "🇳🇴",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  "Saudi Arabia": "🇸🇦",
  Senegal: "🇸🇳",
  Serbia: "🇷🇸",
  Spain: "🇪🇸",
  "South Africa": "🇿🇦",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Tunisia: "🇹🇳",
  Turkey: "🇹🇷",
  Türkiye: "🇹🇷",
  Ukraine: "🇺🇦",
  Uruguay: "🇺🇾",
  USA: "🇺🇸",
  "United States": "🇺🇸",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Algeria: "🇩🇿",
  Chile: "🇨🇱",
  "Czech Republic": "🇨🇿",
  Czechia: "🇨🇿",
  Greece: "🇬🇷",
  Hungary: "🇭🇺",
  Romania: "🇷🇴",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Panama: "🇵🇦",
  Jamaica: "🇯🇲",
  Honduras: "🇭🇳",
  "DR Congo": "🇨🇩",
  "Congo DR": "🇨🇩",
  "Democratic Republic of the Congo": "🇨🇩",
  Congo: "🇨🇬",
  "Cape Verde": "🇨🇻",
  "Cape Verde Islands": "🇨🇻",
  Jordan: "🇯🇴",
  Uzbekistan: "🇺🇿",
  "United Arab Emirates": "🇦🇪",
  UAE: "🇦🇪",
  Iraq: "🇮🇶",
  Bolivia: "🇧🇴",
  Venezuela: "🇻🇪",
  "Bosnia-Herzegovina": "🇧🇦",
  "Bosnia and Herzegovina": "🇧🇦",
  "Curaçao": "🇨🇼",
  Haiti: "🇭🇹",
  Angola: "🇦🇴",
  "Burkina Faso": "🇧🇫",
  Mali: "🇲🇱",
  Guinea: "🇬🇳",
  Zambia: "🇿🇲",
  Gabon: "🇬🇦",
  Georgia: "🇬🇪",
  Slovakia: "🇸🇰",
  Slovenia: "🇸🇮",
  Albania: "🇦🇱",
  "North Macedonia": "🇲🇰",
  Finland: "🇫🇮",
  "El Salvador": "🇸🇻",
  Guatemala: "🇬🇹",
  "Trinidad and Tobago": "🇹🇹",
  "Trinidad & Tobago": "🇹🇹",
  Iceland: "🇮🇸",
  "Republic of Ireland": "🇮🇪",
  Ireland: "🇮🇪",
  "Northern Ireland": "🏴󠁧󠁢󠁮󠁩󠁴󠁿",
  China: "🇨🇳",
  "China PR": "🇨🇳",
  Oman: "🇴🇲",
  Syria: "🇸🇾",
  Palestine: "🇵🇸",
  Lebanon: "🇱🇧",
  Bahrain: "🇧🇭",
  Kuwait: "🇰🇼",
  Yemen: "🇾🇪",
  "North Korea": "🇰🇵",
  "Korea DPR": "🇰🇵",
  "DPR Korea": "🇰🇵",
  Vietnam: "🇻🇳",
  Thailand: "🇹🇭",
  Indonesia: "🇮🇩",
  Kyrgyzstan: "🇰🇬",
  "Kyrgyz Republic": "🇰🇬",
  Tajikistan: "🇹🇯",
  India: "🇮🇳",
};

const TEAMS_COUNTRY_CODE: Record<string, string> = {
  Argentina: "ar",
  Australia: "au",
  Austria: "at",
  Belgium: "be",
  Brazil: "br",
  Cameroon: "cm",
  Canada: "ca",
  Colombia: "co",
  "Costa Rica": "cr",
  Croatia: "hr",
  Denmark: "dk",
  Ecuador: "ec",
  Egypt: "eg",
  England: "gb-eng",
  France: "fr",
  Germany: "de",
  Ghana: "gh",
  Iran: "ir",
  "IR Iran": "ir",
  Italy: "it",
  "Ivory Coast": "ci",
  "Côte d'Ivoire": "ci",
  "Cote d'Ivoire": "ci",
  Japan: "jp",
  "South Korea": "kr",
  "Korea Republic": "kr",
  Korea: "kr",
  Mexico: "mx",
  Morocco: "ma",
  Netherlands: "nl",
  "New Zealand": "nz",
  Nigeria: "ng",
  Norway: "no",
  Paraguay: "py",
  Peru: "pe",
  Poland: "pl",
  Portugal: "pt",
  Qatar: "qa",
  "Saudi Arabia": "sa",
  Senegal: "sn",
  Serbia: "rs",
  Spain: "es",
  "South Africa": "za",
  Sweden: "se",
  Switzerland: "ch",
  Tunisia: "tn",
  Turkey: "tr",
  Türkiye: "tr",
  Ukraine: "ua",
  Uruguay: "uy",
  USA: "us",
  "United States": "us",
  Wales: "gb-wls",
  Algeria: "dz",
  Chile: "cl",
  "Czech Republic": "cz",
  Czechia: "cz",
  Greece: "gr",
  Hungary: "hu",
  Romania: "ro",
  Scotland: "gb-sct",
  Panama: "pa",
  Jamaica: "jm",
  Honduras: "hn",
  "DR Congo": "cd",
  "Congo DR": "cd",
  "Democratic Republic of the Congo": "cd",
  Congo: "cg",
  "Cape Verde": "cv",
  "Cape Verde Islands": "cv",
  Jordan: "jo",
  Uzbekistan: "uz",
  "United Arab Emirates": "ae",
  UAE: "ae",
  Iraq: "iq",
  Bolivia: "bo",
  Venezuela: "ve",
  "Bosnia-Herzegovina": "ba",
  "Bosnia and Herzegovina": "ba",
  "Curaçao": "cw",
  Haiti: "ht",
  Angola: "ao",
  "Burkina Faso": "bf",
  Mali: "ml",
  Guinea: "gn",
  Zambia: "zm",
  Gabon: "ga",
  Georgia: "ge",
  Slovakia: "sk",
  Slovenia: "si",
  Albania: "al",
  "North Macedonia": "mk",
  Finland: "fi",
  "El Salvador": "sv",
  Guatemala: "gt",
  "Trinidad and Tobago": "tt",
  "Trinidad & Tobago": "tt",
  Iceland: "is",
  "Republic of Ireland": "ie",
  Ireland: "ie",
  "Northern Ireland": "gb-nir",
  China: "cn",
  "China PR": "cn",
  Oman: "om",
  Syria: "sy",
  Palestine: "ps",
  Lebanon: "lb",
  Bahrain: "bh",
  Kuwait: "kw",
  Yemen: "ye",
  "North Korea": "kp",
  "Korea DPR": "kp",
  "DPR Korea": "kp",
  Vietnam: "vn",
  Thailand: "th",
  Indonesia: "id",
  Kyrgyzstan: "kg",
  "Kyrgyz Republic": "kg",
  Tajikistan: "tj",
  India: "in",
};

export function teamFa(name: string | null | undefined): string {
  if (!name) return "—";
  return TEAMS_FA[name] ?? name;
}

export function teamFlag(name: string | null | undefined): string {
  if (!name) return "🏳️";
  return TEAMS_FLAG[name] ?? "🏳️";
}

export function teamFlagUrl(name: string | null | undefined): string | null {
  if (!name) return null;
  const code = TEAMS_COUNTRY_CODE[name];
  if (!code) return null;
  return `https://flagcdn.com/${code.toLowerCase()}.svg`;
}
