// Maps English national-team names (as returned by football-data.org) to Persian.
// Falls back to the original name if not found.
const TEAMS_FA: Record<string, string> = {
  Argentina: "آرژانتین",
  Australia: "استرالیا",
  Austria: "اتریش",
  Belgium: "بلژیک",
  Brazil: "برزیل",
  Cameroon: "کامرون",
  Canada: "کانادا",
  Colombia: "کلمبیا",
  "Costa Rica": "کاستاریکا",
  Croatia: "کرواسی",
  Denmark: "دانمارک",
  Ecuador: "اکوادور",
  Egypt: "مصر",
  England: "انگلیس",
  France: "فرانسه",
  Germany: "آلمان",
  Ghana: "غنا",
  Iran: "ایران",
  "IR Iran": "ایران",
  Italy: "ایتالیا",
  "Ivory Coast": "ساحل عاج",
  Japan: "ژاپن",
  "South Korea": "کره جنوبی",
  "Korea Republic": "کره جنوبی",
  Mexico: "مکزیک",
  Morocco: "مراکش",
  Netherlands: "هلند",
  "New Zealand": "نیوزیلند",
  Nigeria: "نیجریه",
  Norway: "نروژ",
  Paraguay: "پاراگوئه",
  Peru: "پرو",
  Poland: "لهستان",
  Portugal: "پرتغال",
  Qatar: "قطر",
  "Saudi Arabia": "عربستان",
  Senegal: "سنگال",
  Serbia: "صربستان",
  Spain: "اسپانیا",
  "South Africa": "آفریقای جنوبی",
  Sweden: "سوئد",
  Switzerland: "سوئیس",
  Tunisia: "تونس",
  Turkey: "ترکیه",
  Türkiye: "ترکیه",
  Ukraine: "اوکراین",
  Uruguay: "اروگوئه",
  USA: "آمریکا",
  "United States": "آمریکا",
  Wales: "ولز",
  Algeria: "الجزایر",
  Chile: "شیلی",
  "Czech Republic": "جمهوری چک",
  Czechia: "جمهوری چک",
  Greece: "یونان",
  Hungary: "مجارستان",
  Romania: "رومانی",
  Scotland: "اسکاتلند",
  Panama: "پاناما",
  Jamaica: "جامائیکا",
  Honduras: "هندوراس",
  "DR Congo": "کنگو",
  "Cape Verde": "کیپ‌ورد",
  Jordan: "اردن",
  Uzbekistan: "ازبکستان",
  "United Arab Emirates": "امارات",
  Iraq: "عراق",
  Bolivia: "بولیوی",
  Venezuela: "ونزوئلا",
};

export function teamFa(name: string | null | undefined): string {
  if (!name) return "—";
  return TEAMS_FA[name] ?? name;
}
