// Maps English national-team names (as returned by football-data.org) to Persian.
// Falls back to the original name if not found.
const TEAMS_FA: Record<string, string> = {
  Argentina: "آرژانتین",
  Australia: "استرالیا",
  Austria: "اتریش",
  Belgium: "بلژیک",
  Brazil: "برزیل",
  Cameroon: "کامرون",
  Canada: "کانادا",
  Colombia: "کلمبیا",
  "Costa Rica": "کاستاریکا",
  Croatia: "کرواسی",
  Denmark: "دانمارک",
  Ecuador: "اکوادور",
  Egypt: "مصر",
  England: "انگلیس",
  France: "فرانسه",
  Germany: "آلمان",
  Ghana: "غنا",
  Iran: "ایران",
  "IR Iran": "ایران",
  Italy: "ایتالیا",
  "Ivory Coast": "ساحل عاج",
  Japan: "ژاپن",
  "South Korea": "کره جنوبی",
  "Korea Republic": "کره جنوبی",
  Mexico: "مکزیک",
  Morocco: "مراکش",
  Netherlands: "هلند",
  "New Zealand": "نیوزیلند",
  Nigeria: "نیجریه",
  Norway: "نروژ",
  Paraguay: "پاراگوئه",
  Peru: "پرو",
  Poland: "لهستان",
  Portugal: "پرتغال",
  Qatar: "قطر",
  "Saudi Arabia": "عربستان",
  Senegal: "سنگال",
  Serbia: "صربستان",
  Spain: "اسپانیا",
  "South Africa": "آفریقای جنوبی",
  Sweden: "سوئد",
  Switzerland: "سوئیس",
  Tunisia: "تونس",
  Turkey: "ترکیه",
  Türkiye: "ترکیه",
  Ukraine: "اوکراین",
  Uruguay: "اروگوئه",
  USA: "آمریکا",
  "United States": "آمریکا",
  Wales: "ولز",
  Algeria: "الجزایر",
  Chile: "شیلی",
  "Czech Republic": "جمهوری چک",
  Czechia: "جمهوری چک",
  Greece: "یونان",
  Hungary: "مجارستان",
  Romania: "رومانی",
  Scotland: "اسکاتلند",
  Panama: "پاناما",
  Jamaica: "جامائیکا",
  Honduras: "هندوراس",
  "DR Congo": "کنگو",
  "Cape Verde": "کیپ‌ورد",
  Jordan: "اردن",
  Uzbekistan: "ازبکستان",
  "United Arab Emirates": "امارات",
  Iraq: "عراق",
  Bolivia: "بولیوی",
  Venezuela: "ونزوئلا",
  "Bosnia-Herzegovina": "بوسنی و هرزگوین",
  "Cape Verde Islands": "کیپ‌ورد",
  "Congo DR": "کنگو دموکراتیک",
  "Curaçao": "کوراسائو",
  Haiti: "هائیتی",
};

const TEAMS_FLAG: Record<string, string> = {
  Argentina: "🇦🇷",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  Brazil: "🇧🇷",
  Cameroon: "🇨🇲",
  Canada: "🇨🇦",
  Colombia: "🇨🇴",
  "Costa Rica": "🇨🇷",
  Croatia: "🇭🇷",
  Denmark: "🇩🇰",
  Ecuador: "🇪🇨",
  Egypt: "🇪🇬",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Ghana: "🇬🇭",
  Iran: "🇮🇷",
  "IR Iran": "🇮🇷",
  Italy: "🇮🇹",
  "Ivory Coast": "🇨🇮",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  "Korea Republic": "🇰🇷",
  Mexico: "🇲🇽",
  Morocco: "🇲🇦",
  Netherlands: "🇳🇱",
  "New Zealand": "🇳🇿",
  Nigeria: "🇳🇬",
  Norway: "🇳🇴",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  "Saudi Arabia": "🇸🇦",
  Senegal: "🇸🇳",
  Serbia: "🇷🇸",
  Spain: "🇪🇸",
  "South Africa": "🇿🇦",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Tunisia: "🇹🇳",
  Turkey: "🇹🇷",
  Türkiye: "🇹🇷",
  Ukraine: "🇺🇦",
  Uruguay: "🇺🇾",
  USA: "🇺🇸",
  "United States": "🇺🇸",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Algeria: "🇩🇿",
  Chile: "🇨🇱",
  "Czech Republic": "🇨🇿",
  Czechia: "🇨🇿",
  Greece: "🇬🇷",
  Hungary: "🇭🇺",
  Romania: "🇷🇴",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Panama: "🇵🇦",
  Jamaica: "🇯🇲",
  Honduras: "🇭🇳",
  "DR Congo": "🇨🇩",
  "Cape Verde": "🇨🇻",
  Jordan: "🇯🇴",
  Uzbekistan: "🇺🇿",
  "United Arab Emirates": "🇦🇪",
  Iraq: "🇮🇶",
  Bolivia: "🇧🇴",
  Venezuela: "🇻🇪",
  "Bosnia-Herzegovina": "🇧🇦",
  "Cape Verde Islands": "🇨🇻",
  "Congo DR": "🇨🇩",
  "Curaçao": "🇨🇼",
  Haiti: "🇭🇹",
};

export function teamFa(name: string | null | undefined): string {
  if (!name) return "—";
  return TEAMS_FA[name] ?? name;
}

export function teamFlag(name: string | null | undefined): string {
  if (!name) return "🏳️";
  return TEAMS_FLAG[name] ?? "🏳️";
}

